server:
  port: 8085

spring:
  application:
    name: service-map
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-map?characterEncoding=utf-8&serverTimezone=GMT%2B8


amap:
  key: 08449262cb3620f7487990f953bb3ebd
  sid: 914016
